# Generated by Django 3.1.2 on 2020-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
