# Generated by Django 3.1.2 on 2020-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thirdyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_score', models.CharField(blank=True, max_length=10, null=True)),
                ('age_sum', models.BooleanField(blank=True, max_length=10)),
                ('letter_sum', models.BooleanField(blank=True, max_length=10)),
            ],
        ),
    ]
